name: Brew Audit (Online/Github Repo)

on:
  workflow_dispatch:

jobs:
  audit:
    name: Run brew audit on the online (github repo) tod formula
    runs-on: macos-latest

    steps:
      - name: Tap tod formula
        run: brew tap tod-org/tod

      - name: Update Homebrew & formula
        run: brew update


      - name: Audit tod formula
        run: brew audit --strict --online --new tod