name: Brew Audit (Local Repo)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch of homebrew-tod to audit"
        required: false
        default: "main"

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - name: Checkout homebrew-tod
        uses: actions/checkout@v4
        with:
          repository: tod-org/homebrew-tod
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 1

      - name: Tap local path & run all checks
        shell: bash
        run: |
          set -euo pipefail

          CANON_TAP="tod-org/tod"
          FORMULA="tod"

          echo "==> Current branch: ${{ github.event.inputs.branch }}"
          echo "PWD: $(pwd)"
          ls -la

          # Ensure clean slate, then tap using the local path
          brew untap "$CANON_TAP" || true
          brew tap "tod-org/homebrew-tod" "$(pwd)"

          # Verify the tap
          brew tap-info --installed "$CANON_TAP"

          echo "==> readall"
          brew readall "$CANON_TAP"

          echo "==> style"
          brew style "$CANON_TAP/$FORMULA"

          echo "==> audit --strict --online"
          brew audit --strict --online "$CANON_TAP/$FORMULA"
