name: Brew Audit (Local Repo)

on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - name: Checkout homebrew-tod
        uses: actions/checkout@v4
        with:
          repository: tod-org/homebrew-tod
          ref: ${{ github.ref_name }}
          fetch-depth: 1

      - name: Tap local path & run all checks
        shell: bash
        run: |
          set -euo pipefail

          CANON_TAP="tod-org/tod"
          FORMULA="tod"

          echo "==> Branch: ${{ github.ref_name }}"
          echo "PWD: $(pwd)"
          ls -la

          # Tap using the local path
          brew tap "tod-org/homebrew-tod" "$(pwd)"

          # Verify the tap
          brew tap-info --installed "$CANON_TAP"

          echo "==> readall"
          brew readall "$CANON_TAP"

          echo "==> style"
          brew style "$CANON_TAP/$FORMULA"

          echo "==> audit --strict --online"
          brew audit --strict --online "$CANON_TAP/$FORMULA"
