name: Brew Audit (Local Repo)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref of homebrew-tod to audit (branch, tag, or SHA)"
        type: string
        required: false
        default: "main"
      formula:
        description: "Formula name to audit (e.g., tod)"
        type: string
        required: false
        default: "tod"
      online:
        description: "Run online checks (recommended)"
        type: boolean
        required: false
        default: true

permissions:
  contents: read

concurrency:
  group: brew-audit
  cancel-in-progress: false

jobs:
  audit:
    runs-on: macos-latest

    steps:
      - name: Create app token (tod-deploy)
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.TODD_APP_ID }}
          private-key: ${{ secrets.TODD_PRIVATE_KEY }}
          owner: tod-org
          repositories: homebrew-tod

      - name: Checkout homebrew-tod
        uses: actions/checkout@v4
        with:
          repository: tod-org/homebrew-tod
          ref: ${{ inputs.ref }}
          fetch-depth: 1
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Tap local path & audit
        env:
          HOMEBREW_NO_AUTO_UPDATE: "1"
          HOMEBREW_NO_ANALYTICS: "1"
        run: |
          set -euo pipefail

          CANON_TAP="tod-org/tod"
          FORMULA="${{ inputs.formula }}"
          ONLINE_FLAG=""
          if [[ "${{ inputs.online }}" == "true" ]]; then
            ONLINE_FLAG="--online"
          fi

          echo "PWD: $(pwd)"
          echo "Contents:"
          ls -la
          echo "Formula dir:"
          ls -la Formula || true

          # Ensure clean slate, then tap using the canonical name with LOCAL PATH
          brew untap "$CANON_TAP" || true
          brew tap "$CANON_TAP" "$(pwd)"

          # Sanity: make sure the tap is registered and points to this path
          brew tap-info --installed "$CANON_TAP"

          echo "==> readall"
          brew readall "$CANON_TAP"

          echo "==> style"
          brew style "$CANON_TAP/$FORMULA"

          echo "==> audit --strict $ONLINE_FLAG"
          brew audit --strict $ONLINE_FLAG "$CANON_TAP/$FORMULA"
