name: Update Homebrew Formula from tod

# Triggered remotely by 'repository_dispatch' from tod-org/tod
# Also supports manual triggering via workflow_dispatch
on:
  repository_dispatch:
    types: [update-homebrew]

  workflow_dispatch:

# Allows pushing commits to the repository
permissions:
  contents: write

jobs:
  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the homebrew-tod repo and ensure we're on the main branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      # Step 2: Fetch the latest release tag from the tod repo (tod-org/tod)
      #         Strip the leading 'v' to pass just the version to the Ruby script (e.g., 0.8.0)
      # jq comes preinstalled on runners; dont' need to install/update
      - name: Fetch latest release tag from tod repo
        id: get_version
        run: |
          tag=$(curl -s https://api.github.com/repos/tod-org/tod/releases/latest | jq -r .tag_name)
          version=${tag#v}
          echo "Latest tag: $tag"
          echo "Version without v: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      # Step 3: Set up Ruby so we can run the formula update script
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Step 4: Run the Ruby script to update the formula with correct version and SHA256s
      - name: Run formula updater
        run: |
          ruby scripts/update_formula.rb ${{ steps.get_version.outputs.version }}

      # Step 5: Show a diff of what changed (useful for debugging)
      - name: Show diff
        run: git --no-pager diff Formula/tod.rb || true

      # Step 6: Commit and push changes — only if Formula/tod.rb was actually modified
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Check for changes and commit only if there are any
          if ! git diff --quiet Formula/tod.rb; then
            echo "✅ Changes detected. Committing..."
            git add Formula/tod.rb
            git commit -m "Update formula to version ${{ steps.get_version.outputs.version }}"
            git push
          else
            echo "ℹ️ No changes to commit."
          fi
